name: 'Setup Python Environment'
description: 'Sets up Python with pip cache and installs requirements'

inputs:
  python-version:
    description: 'Python version to install'
    required: false
    default: '3.11'
  working-directory:
    description: 'Directory containing requirements.txt'
    required: true
  install-dev:
    description: 'Also install requirements-dev.txt if it exists'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
        cache-dependency-path: ${{ inputs.working-directory }}/requirements*.txt

    - name: Install dependencies
      shell: bash
      run: |
        cd ${{ inputs.working-directory }}
        pip install --upgrade pip
        pip install -r requirements.txt
        if [ "${{ inputs.install-dev }}" = "true" ] && [ -f requirements-dev.txt ]; then
          pip install -r requirements-dev.txt
        fi
