"""
Tests for the public unsubscribe endpoint and token helpers.

Covers:
- _make_unsubscribe_token produces deterministic output
- _verify_token accepts valid token
- _verify_token rejects tampered token
- GET /public/unsubscribe with valid token stamps unsubscribed_at and redirects
- GET /public/unsubscribe with invalid token returns 400
- GET /public/unsubscribe is idempotent (second call is a no-op, still redirects)
- GET /public/unsubscribe when INTERNAL_API_KEY is not set returns 500
- DripService._make_unsubscribe_url produces URL containing uid and tok
- Cross-module round-trip: URL from drip_service validates in public_unsubscribe
- Settings.effective_unsubscribe_secret falls back to internal_api_key when UNSUBSCRIBE_SECRET not set
"""

from unittest.mock import AsyncMock, MagicMock, patch
from uuid import uuid4

from fastapi import FastAPI
from fastapi.testclient import TestClient

from api.v1.public_unsubscribe import _make_unsubscribe_token, _verify_token, router

# ---------------------------------------------------------------------------
# Token helpers
# ---------------------------------------------------------------------------


def test_token_deterministic():
    uid = str(uuid4())
    assert _make_unsubscribe_token(uid, "secret") == _make_unsubscribe_token(uid, "secret")


def test_token_different_for_different_uid():
    tok_a = _make_unsubscribe_token("uid-a", "secret")
    tok_b = _make_unsubscribe_token("uid-b", "secret")
    assert tok_a != tok_b


def test_token_different_for_different_secret():
    uid = str(uuid4())
    assert _make_unsubscribe_token(uid, "s1") != _make_unsubscribe_token(uid, "s2")


def test_token_length():
    tok = _make_unsubscribe_token("uid", "secret")
    assert len(tok) == 32


def test_verify_token_accepts_valid():
    uid = str(uuid4())
    tok = _make_unsubscribe_token(uid, "secret")
    assert _verify_token(uid, tok, "secret") is True


def test_verify_token_rejects_tampered():
    uid = str(uuid4())
    tok = _make_unsubscribe_token(uid, "secret")
    assert _verify_token(uid, tok[:-1] + "x", "secret") is False


def test_verify_token_rejects_wrong_uid():
    tok = _make_unsubscribe_token("uid-a", "secret")
    assert _verify_token("uid-b", tok, "secret") is False


# ---------------------------------------------------------------------------
# DripService URL helper
# ---------------------------------------------------------------------------


def test_drip_service_make_unsubscribe_url():
    from services.drip_service import _make_unsubscribe_url

    uid = str(uuid4())
    with patch("services.drip_service.get_settings") as mock_settings:
        mock_settings.return_value.effective_unsubscribe_secret = "test-secret"
        url = _make_unsubscribe_url(uid)

    assert f"uid={uid}" in url
    assert "tok=" in url
    assert url.startswith("https://rateshift.app/api/v1/public/unsubscribe")


def test_round_trip_drip_url_validates_in_endpoint():
    """Token generated by drip_service must validate in the unsubscribe endpoint.

    This cross-module test guards against HMAC key/algorithm drift between the
    URL producer (drip_service._make_unsubscribe_url) and the URL consumer
    (public_unsubscribe._verify_token).  If either side changes its signing
    logic without the other, this test fails.
    """
    from urllib.parse import parse_qs, urlparse

    from services.drip_service import _make_unsubscribe_url

    uid = str(uuid4())
    shared_secret = "round-trip-test-secret"

    with patch("services.drip_service.get_settings") as mock_settings:
        mock_settings.return_value.effective_unsubscribe_secret = shared_secret
        url = _make_unsubscribe_url(uid)

    parsed = urlparse(url)
    qs = parse_qs(parsed.query)
    extracted_uid = qs["uid"][0]
    extracted_tok = qs["tok"][0]

    assert extracted_uid == uid
    assert _verify_token(extracted_uid, extracted_tok, shared_secret) is True


def test_round_trip_rejects_wrong_secret():
    """Token generated with one secret must NOT validate with a different secret."""
    from urllib.parse import parse_qs, urlparse

    from services.drip_service import _make_unsubscribe_url

    uid = str(uuid4())
    with patch("services.drip_service.get_settings") as mock_settings:
        mock_settings.return_value.effective_unsubscribe_secret = "producer-secret"
        url = _make_unsubscribe_url(uid)

    parsed = urlparse(url)
    qs = parse_qs(parsed.query)
    tok = qs["tok"][0]

    assert _verify_token(uid, tok, "different-secret") is False


# ---------------------------------------------------------------------------
# Endpoint tests
# ---------------------------------------------------------------------------


def _make_app(db_mock):
    app = FastAPI()

    async def _override_db():
        yield db_mock

    from api.dependencies import get_db_session

    app.dependency_overrides[get_db_session] = _override_db
    app.include_router(router, prefix="/api/v1")
    return app


def _make_db(updated=True):
    db = AsyncMock()
    db.commit = AsyncMock()
    result = MagicMock()
    result.fetchone = MagicMock(return_value=("uid",) if updated else None)
    db.execute = AsyncMock(return_value=result)
    return db


class TestUnsubscribeEndpoint:
    def test_valid_token_redirects(self):
        uid = str(uuid4())
        tok = _make_unsubscribe_token(uid, "test-secret")
        db = _make_db(updated=True)
        app = _make_app(db)

        with patch("api.v1.public_unsubscribe._settings") as ms:
            ms.effective_unsubscribe_secret = "test-secret"
            client = TestClient(app, follow_redirects=False)
            resp = client.get(f"/api/v1/public/unsubscribe?uid={uid}&tok={tok}")

        assert resp.status_code == 302
        assert resp.headers["location"] == "https://rateshift.app/unsubscribed"
        db.commit.assert_awaited_once()

    def test_invalid_token_returns_400(self):
        uid = str(uuid4())
        db = _make_db()
        app = _make_app(db)

        with patch("api.v1.public_unsubscribe._settings") as ms:
            ms.effective_unsubscribe_secret = "test-secret"
            client = TestClient(app, follow_redirects=False)
            resp = client.get(
                f"/api/v1/public/unsubscribe?uid={uid}&tok=badtoken123456789012345678901234"
            )

        assert resp.status_code == 400

    def test_idempotent_still_redirects(self):
        uid = str(uuid4())
        tok = _make_unsubscribe_token(uid, "test-secret")
        db = _make_db(updated=False)  # already unsubscribed — UPDATE returns no row
        app = _make_app(db)

        with patch("api.v1.public_unsubscribe._settings") as ms:
            ms.effective_unsubscribe_secret = "test-secret"
            client = TestClient(app, follow_redirects=False)
            resp = client.get(f"/api/v1/public/unsubscribe?uid={uid}&tok={tok}")

        assert resp.status_code == 302

    def test_missing_secret_returns_500(self):
        uid = str(uuid4())
        tok = _make_unsubscribe_token(uid, "")
        db = _make_db()
        app = _make_app(db)

        with patch("api.v1.public_unsubscribe._settings") as ms:
            ms.effective_unsubscribe_secret = ""
            client = TestClient(app, follow_redirects=False)
            resp = client.get(f"/api/v1/public/unsubscribe?uid={uid}&tok={tok}")

        assert resp.status_code == 500


# ---------------------------------------------------------------------------
# Settings.effective_unsubscribe_secret fallback behavior
# ---------------------------------------------------------------------------


def test_effective_unsubscribe_secret_uses_dedicated_key_when_set():
    from config.settings import Settings

    s = Settings(
        INTERNAL_API_KEY="internal-key",
        UNSUBSCRIBE_SECRET="dedicated-unsub-key",
        DATABASE_URL="postgresql://x",
    )
    assert s.effective_unsubscribe_secret == "dedicated-unsub-key"


def test_effective_unsubscribe_secret_falls_back_to_internal_api_key():
    from config.settings import Settings

    s = Settings(
        INTERNAL_API_KEY="internal-key",
        DATABASE_URL="postgresql://x",
    )
    # No UNSUBSCRIBE_SECRET set — must fall back
    assert s.effective_unsubscribe_secret == "internal-key"


def test_effective_unsubscribe_secret_empty_when_neither_set():
    from config.settings import Settings

    s = Settings(DATABASE_URL="postgresql://x")
    assert s.effective_unsubscribe_secret == ""
